### get request
GET http://localhost:8000

### get single or all tasks from server
GET http://localhost:8000/api/v1/task

### post task to server
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "Coding",
    "hr": "20"
}

### 
PATCH http://localhost:8000/api/v1/task
Content-Type: application/json

{
"_id": "62676c6d5d518a378ba59ed9",
"task": "Watching TV"
}


### delete task to server
DELETE http://localhost:8000/api/v1/task/626767eb067874fb76316728
